// Overlay (break screen) strings. Keep `de` and `en` in full parity.
// Titles shown inside the ring use a no-break space before "–" so a line never starts with the dash.

export default {
  de: {
    appName: 'AugenPause',
    docTitle: 'AugenPause – Pause',

    titleShort: 'Augenpause',
    titleLong: 'Lange Pause',
    subtitleShort: 'Schau in die Ferne und entspann deine Augen',
    subtitleLong: 'Steh auf, beweg dich und gönn deinen Augen Ruhe',

    inhale: 'Einatmen',
    exhale: 'Ausatmen',

    cycleShort: 'Pause {n} von {total} bis zur langen Pause',
    cycleLong: 'Lange Pause – Zyklus geschafft',
    running: 'Pause läuft',
    endsAt: 'endet um {time}',

    snoozeLabel: 'Verschieben',
    snoozeMin: '+{min} Min',
    snoozeOptionAria: 'Pause um {min} Minuten verschieben',
    snoozeLeft: '(noch {n}×)',
    skipClick: 'Überspringen',
    skipHold: 'Gedrückt halten zum Überspringen',
    skipHolding: 'Weiter halten …',
    skipping: 'Wird übersprungen …',
    strictName: 'Pflicht-Pause',
    strictEnds: 'endet automatisch um {time}',
    // always-present fallback chip (index.html): must make sense on its own, even on a page that failed to render
    lockFallback: 'Pflicht-Pause – der Bildschirm wird nach Ablauf freigegeben',

    graceTitle: 'Gerade ungünstig?',
    graceAction: 'Pause verschieben',
    graceHint: '= {min} Min verschieben',
    escHint: 'zum Verschieben',

    hydration: 'Guter Moment für ein Glas Wasser',
    drank: 'Getrunken',
    drankThanks: 'Eingetragen – prost!',

    exerciseLabel: 'Übung',
    exerciseCount: '{n} von {total}',

    doneTitle: 'Geschafft – weiter geht’s',
    doneSub: 'Deine Augen sagen danke',
    endedTitle: 'Pause beendet',
    endedSub: 'Bis zur nächsten Pause',
    snoozedTitle: 'Pause verschoben',
    snoozedSub: 'Sie kommt in {min} Min wieder',
    meetingTitle: 'Pause unterbrochen – Meeting erkannt',
    meetingSub: 'Sie wird nach dem Meeting nachgeholt',

    srStart: '{title} gestartet. Noch {time}.',
    srGrace: 'Escape drücken, um die Pause zu verschieben.',
    srStrict: 'Pflicht-Pause, sie endet automatisch um {time}.',
    srMinutes: 'Noch {n} Minuten',
    srMinute: 'Noch 1 Minute',
    'sr.completed': 'Pause geschafft.',
    'sr.ended': 'Pause beendet.',
    'sr.snoozed': 'Pause verschoben.',
    'sr.meeting': 'Pause unterbrochen, Meeting erkannt.',
    durMinutes: '{n} Minuten',
    durMinute: '1 Minute',
    durSeconds: '{n} Sekunden',

    'ex.far.title': '20-20-20',
    'ex.far.text': 'Schau 20 Sekunden auf einen Punkt in 6 m Entfernung',
    'ex.blink.title': 'Bewusst blinzeln',
    'ex.blink.text': 'Blinzle 10× ganz langsam und bewusst',
    'ex.roll.title': 'Augen kreisen',
    'ex.roll.text': 'Lass die Augen je 5× links- und rechtsherum kreisen',
    'ex.nearfar.title': 'Nah-Fern-Fokus',
    'ex.nearfar.text': 'Wechsle den Blick zwischen Daumen und Horizont',
    'ex.palming.title': 'Palming',
    'ex.palming.text': 'Reib die Hände warm und leg sie sanft über die Augen',
    'ex.eight.title': 'Acht nachzeichnen',
    'ex.eight.text': 'Zeichne mit den Augen langsam eine liegende Acht',
    'ex.stretch.title': 'Aufstehen & strecken',
    'ex.stretch.text': 'Steh auf und streck die Arme weit nach oben',
    'ex.shoulders.title': 'Schultern kreisen',
    'ex.shoulders.text': 'Kreise die Schultern langsam nach hinten',
    'ex.water.title': 'Ein Glas Wasser trinken',
    'ex.water.text': 'Trink in Ruhe ein Glas Wasser',
  },

  en: {
    appName: 'AugenPause',
    docTitle: 'AugenPause – Break',

    titleShort: 'Eye break',
    titleLong: 'Long break',
    subtitleShort: 'Look into the distance and let your eyes relax',
    subtitleLong: 'Stand up, move around and give your eyes a rest',

    inhale: 'Breathe in',
    exhale: 'Breathe out',

    cycleShort: 'Break {n} of {total} until the long break',
    cycleLong: 'Long break – cycle complete',
    running: 'Break in progress',
    endsAt: 'ends at {time}',

    snoozeLabel: 'Snooze',
    snoozeMin: '+{min} min',
    snoozeOptionAria: 'Postpone the break by {min} minutes',
    snoozeLeft: '({n}× left)',
    skipClick: 'Skip',
    skipHold: 'Press and hold to skip',
    skipHolding: 'Keep holding …',
    skipping: 'Skipping …',
    strictName: 'Mandatory break',
    strictEnds: 'ends automatically at {time}',
    lockFallback: 'Mandatory break – your screen is released once the time is up',

    graceTitle: 'Bad timing?',
    graceAction: 'Postpone the break',
    graceHint: '= snooze for {min} min',
    escHint: 'to snooze',

    hydration: 'Good moment for a glass of water',
    drank: 'Done',
    drankThanks: 'Logged – cheers!',

    exerciseLabel: 'Exercise',
    exerciseCount: '{n} of {total}',

    doneTitle: 'Well done – back to it',
    doneSub: 'Your eyes say thank you',
    endedTitle: 'Break ended',
    endedSub: 'See you at the next break',
    snoozedTitle: 'Break postponed',
    snoozedSub: 'It will be back in {min} min',
    meetingTitle: 'Break interrupted – meeting detected',
    meetingSub: 'It will be made up after the meeting',

    srStart: '{title} started. {time} remaining.',
    srGrace: 'Press Escape to postpone the break.',
    srStrict: 'Mandatory break, it ends automatically at {time}.',
    srMinutes: '{n} minutes remaining',
    srMinute: '1 minute remaining',
    'sr.completed': 'Break complete.',
    'sr.ended': 'Break ended.',
    'sr.snoozed': 'Break postponed.',
    'sr.meeting': 'Break interrupted, meeting detected.',
    durMinutes: '{n} minutes',
    durMinute: '1 minute',
    durSeconds: '{n} seconds',

    'ex.far.title': '20-20-20',
    'ex.far.text': 'Look at something 20 ft (6 m) away for 20 seconds',
    'ex.blink.title': 'Blink mindfully',
    'ex.blink.text': 'Blink slowly and deliberately 10 times',
    'ex.roll.title': 'Eye circles',
    'ex.roll.text': 'Roll your eyes 5× clockwise, then 5× counter-clockwise',
    'ex.nearfar.title': 'Near–far focus',
    'ex.nearfar.text': 'Shift your gaze between your thumb and the horizon',
    'ex.palming.title': 'Palming',
    'ex.palming.text': 'Rub your hands warm and gently cup them over your eyes',
    'ex.eight.title': 'Trace a figure eight',
    'ex.eight.text': 'Slowly trace a sideways eight with your eyes',
    'ex.stretch.title': 'Stand up & stretch',
    'ex.stretch.text': 'Stand up and reach your arms high above your head',
    'ex.shoulders.title': 'Shoulder rolls',
    'ex.shoulders.text': 'Slowly roll your shoulders backwards',
    'ex.water.title': 'Drink a glass of water',
    'ex.water.text': 'Take a moment and drink a glass of water',
  },
};
