// Dashboard strings (de + en, complete parity). Used via createT() from ../shared/i18n.js.

export default {
  de: {
    app_name: 'AugenPause',
    view_error: 'Dieser Bereich konnte nicht geladen werden.',

    // ---- navigation ----------------------------------------------------------------
    nav_label: 'Hauptnavigation',
    nav_overview: 'Übersicht',
    nav_settings: 'Einstellungen',
    nav_stats: 'Statistik',
    nav_exercises: 'Übungen',
    nav_about: 'Über',

    // ---- phases --------------------------------------------------------------------
    phase_work: 'Arbeitsphase',
    phase_warning: 'Gleich Pause',
    phase_break_short: 'Kurze Pause',
    phase_break_long: 'Lange Pause',
    phase_meeting: 'Im Meeting',
    phase_paused: 'Pausiert',
    phase_away: 'Abwesend',
    phase_off_hours: 'Feierabend',
    meeting_active_chip: 'Meeting aktiv',

    mini_until_break: 'bis zur Pause',
    mini_remaining: 'verbleibend',
    mini_meeting: 'Pause folgt danach',
    mini_until_resume: 'bis Fortsetzen',
    mini_indefinite: 'bis du fortsetzt',
    mini_frozen: 'Timer angehalten',
    mini_no_reminders: 'keine Erinnerungen',
    mini_next_start: 'nächster Start',

    // ---- toasts --------------------------------------------------------------------
    toast_saved: 'Gespeichert',
    toast_save_failed: 'Speichern fehlgeschlagen',
    toast_action_failed: 'Aktion gerade nicht möglich',
    toast_settings_reset: 'Einstellungen zurückgesetzt',
    toast_reset_blocked: 'Während einer laufenden Pause nicht möglich',
    toast_stats_reset: 'Statistik zurückgesetzt',
    toast_resumed: 'Erinnerungen fortgesetzt',
    toast_break_ended: 'Pause beendet',
    toast_snoozed: 'Pause um {duration} verschoben',
    toast_skipped: 'Pause übersprungen',
    toast_paused_for: 'Pausiert für {duration}',
    toast_paused_tomorrow: 'Pausiert bis morgen',
    toast_paused: 'Pausiert, bis du fortsetzt',
    toast_timer_reset: 'Timer zurückgesetzt',
    toast_drink: 'Prost! Glas eingetragen',
    toast_position_reset: 'Widget-Position zurückgesetzt',

    // ---- overview ----------------------------------------------------------------------
    overview_title: 'Übersicht',
    greet_night: 'Gute Nacht',
    greet_morning: 'Guten Morgen',
    greet_day: 'Hallo',
    greet_evening: 'Guten Abend',
    hero_label: 'Aktueller Status',
    today_label: 'Heute',

    act_resume: 'Fortsetzen',
    act_end_break: 'Pause beenden',
    act_break_now: 'Jetzt Pause',
    act_edit_hours: 'Arbeitszeiten bearbeiten',
    act_snooze: 'Verschieben',
    act_snooze_options: 'Verschieben um …',
    act_skip: 'Überspringen',
    act_meeting_mode: 'Meeting-Modus',
    act_pause: 'Pausieren',
    act_reset_timer: 'Timer zurücksetzen',

    menu_snooze_heading: 'Pause verschieben um',
    menu_meeting_heading: 'Keine Pausen während des Meetings',
    menu_pause_heading: 'Erinnerungen pausieren',
    pause_tomorrow: 'Bis morgen',
    pause_indefinite: 'Bis ich fortsetze',

    snooze_grace_any: 'Schonfrist – Verschieben immer möglich',
    snooze_left: 'Noch {n}× verschiebbar',
    snooze_none_left: 'Nicht mehr verschiebbar',
    snooze_disabled: 'Verschieben ist deaktiviert',
    snooze_strict: 'Pflicht-Pause – nicht verschiebbar',
    snooze_used: '{count}× verschoben · noch {left}×',

    break_short_lc: 'kurze Pause',
    break_long_lc: 'lange Pause',

    center_until_break: 'bis zur Pause',
    center_break_soon: 'gleich Pause',
    center_remaining: 'verbleibend',
    center_in_meeting: 'im Meeting',
    center_until_resume: 'bis Fortsetzen',
    center_indefinite: 'unbegrenzt',
    center_frozen: 'angehalten',
    center_next_start: 'nächster Start',

    title_next: 'Nächste: {type} · {duration}',
    title_meeting: 'Meeting erkannt – Pause wird danach nachgeholt',
    title_break_short: 'Zeit für deine Augen',
    title_break_long: 'Zeit, aufzustehen und dich zu bewegen',
    title_paused: 'Erinnerungen pausiert',
    title_away: 'Du bist gerade nicht am Rechner',
    title_off_hours: 'Außerhalb deiner Arbeitszeit',

    detail_starts_at: 'Beginnt um {time}',
    detail_this_long: 'Diesmal eine lange Pause',
    detail_long_in_one: 'Lange Pause nach der nächsten Pause',
    detail_long_in_other: 'Lange Pause in {n} Pausen',
    detail_meeting_since: 'Im Meeting seit {time}',
    detail_meeting_after: 'Die {type} ({duration}) startet kurz nach dem Meeting',
    detail_ends_at: 'Endet um {time}',
    detail_paused_until: 'Bis {time}',
    detail_paused_until_day: 'Bis {day}, {time}',
    detail_paused_indefinite: 'Bis du fortsetzt',
    detail_paused_hint: 'Nach dem Fortsetzen beginnt eine neue Arbeitsphase',
    detail_away_since: 'Abwesend seit {time}',
    detail_away_rule: 'Ab {duration} zählt die Abwesenheit als Pause',
    detail_hours: '{days} · {start}–{end}',
    detail_next_start: 'Nächster Start: {day}, {time}',

    notice_grace: 'Schonfrist: noch {s} s – Verschieben ist jetzt immer möglich.',
    notice_strict: 'Pflicht-Pause: Diese Pause läuft bis zum Ende – danach wird der Bildschirm automatisch freigegeben.',

    tile_breaks: 'Pausen gemacht',
    tile_screen: 'Bildschirmzeit',
    tile_water: 'Wasser',
    tile_quote: 'Pausen-Quote',
    sub_skipped_one: '{n} übersprungen',
    sub_skipped_other: '{n} übersprungen',
    sub_natural_one: '{n} natürlich',
    sub_natural_other: '{n} natürlich',
    sub_snoozed_one: '{n}× verschoben',
    sub_snoozed_other: '{n}× verschoben',
    sub_break_time: '{duration} in Pausen',
    sub_screen_hint: 'Aktive Zeit heute',
    sub_water_ml: '{ml} von {goal}',
    sub_water_next: 'Nächste Erinnerung in {duration}',
    sub_water_goal: 'Tagesziel erreicht',
    sub_quote_empty: 'Noch keine Pausen heute',
    sub_quote: '{done} von {total} Pausen',
    water_undo: 'Letztes Glas zurücknehmen',
    water_add: 'Glas Wasser eintragen',
    water_due: 'Zeit für ein Glas Wasser',

    tip_title: 'Tipp des Tages',
    tip_prev: 'Vorheriger Tipp',
    tip_next: 'Nächster Tipp',
    tip_0: 'Folge der 20-20-20-Regel: Schau alle 20 Minuten für 20 Sekunden auf etwas, das rund 6 Meter entfernt ist.',
    tip_1: 'Am Bildschirm blinzeln wir bis zu 60 % seltener. Blinzle bewusst, um trockenen Augen vorzubeugen.',
    tip_2: 'Der Monitor sollte etwa eine Armlänge entfernt stehen – die Oberkante auf oder knapp unter Augenhöhe.',
    tip_3: 'Passe die Helligkeit an die Umgebung an: Der Bildschirm sollte nicht heller sein als der Raum um dich herum.',
    tip_4: 'Vermeide Blendung: Stelle den Bildschirm möglichst im rechten Winkel zum Fenster auf.',
    tip_5: 'Trinke regelmäßig Wasser – schon leichter Flüssigkeitsmangel kann die Augen trocken machen.',
    tip_6: 'Tageslicht tut gut: Verbringe deine lange Pause, wenn möglich, draußen.',
    tip_7: 'Vergrößere lieber die Schrift, statt dich zum Bildschirm vorzubeugen – das entlastet Augen und Nacken.',
    tip_8: 'Trockene Heizungsluft? Regelmäßiges Lüften hilft auch deinen Augen.',
    tip_9: 'Lass deine Sehstärke regelmäßig prüfen – und erwähne dabei, wie viel du am Bildschirm arbeitest.',
    tip_10: 'Ein ausgewogener Kontrast ist wichtiger als Hell oder Dunkel – wähle, was sich für dich angenehm anfühlt.',
    tip_11: 'Palming entspannt: Lege die hohlen Hände über die geschlossenen Augen und atme eine Minute ruhig.',
    tip_12: 'Häufige kurze Pausen wirken besser als seltene lange – Regelmäßigkeit ist der Schlüssel.',
    tip_13: 'Greif in der Pause nicht zum Handy – das ist für deine Augen keine Erholung.',

    // weekdays (0 = Sunday)
    day_short_0: 'So',
    day_short_1: 'Mo',
    day_short_2: 'Di',
    day_short_3: 'Mi',
    day_short_4: 'Do',
    day_short_5: 'Fr',
    day_short_6: 'Sa',
    days_all: 'Täglich',

    // ---- settings --------------------------------------------------------------------
    settings_title: 'Einstellungen',
    settings_subtitle: 'Änderungen werden sofort übernommen.',
    jump_label: 'Zu Abschnitt springen',

    err_end_after_start: 'Das Ende muss nach dem Beginn liegen.',
    err_invalid: 'Dieser Wert ist nicht gültig.',
    err_generic: 'Einige Änderungen konnten nicht übernommen werden.',
    err_days_empty: 'Mindestens ein Tag muss ausgewählt sein.',

    value_off: 'Aus',
    value_click: 'Klick',
    value_never: 'Nie',
    value_opacity: 'Deckkraft {n} %',
    unit_glasses: 'Gläser',

    grp_timer: 'Timer',
    grp_timer_desc: 'Wie oft und wie lange du Pausen machst.',
    set_preset: 'Vorlage',
    set_preset_help: 'Bewährte Rhythmen – oder eigene Werte.',
    preset_halfhour: 'Halbstündlich',
    preset_hourly: 'Stündlich',
    preset_202020: '20-20-20',
    preset_pomodoro: 'Pomodoro',
    preset_custom: 'Benutzer\u00ADdefiniert',
    preset_custom_meta: 'Eigene Werte',
    summary_short_seconds: 'Alle {work} eine {n}-Sekunden-Pause',
    summary_short_minutes: 'Alle {work} eine {n}-Min-Pause',
    summary_short_mixed: 'Alle {work} eine Pause von {duration}',
    summary_long: ', jede {nth} Pause {duration} lang.',
    summary_end: '.',
    set_work: 'Arbeitszeit',
    set_work_help: 'Zeit bis zur nächsten Pause.',
    set_short: 'Kurze Pause',
    set_short_help: 'Schon 20 Sekunden helfen – ideal sind 1 bis 5 Minuten.',
    set_long_enabled: 'Lange Pause',
    set_long_enabled_help: 'Regelmäßig eine längere Pause zum Aufstehen und Bewegen.',
    set_long_duration: 'Dauer der langen Pause',
    set_long_duration_help: 'Genug Zeit, um aufzustehen und etwas zu trinken.',
    set_long_every: 'Jede N. Pause',
    set_long_every_help: 'Wie oft eine Pause zur langen Pause wird.',

    grp_meeting: 'Meetings & Unterbrechungen',
    grp_meeting_short: 'Meetings',
    grp_meeting_desc: 'Damit dich eine Pause nie mitten im Gespräch überrascht. Meetings verschieben die Pause nur, bevor sie beginnt – eine laufende Pflicht-Pause endet nur nach Ablauf.',
    set_meeting_detect: 'Meetings automatisch erkennen',
    set_meeting_detect_help: 'Windows/Linux: Kamera oder Mikrofon aktiv · macOS: Call-Apps wie Zoom, Teams, Meet',
    set_warn: 'Vorwarnung',
    set_warn_help: 'Kündigt die Pause vorher an – mit Ein-Klick-Verschieben.',
    set_show_on_warning: 'Widget bei Vorwarnung einblenden',
    set_show_on_warning_help: 'Zeigt das ausgeblendete Widget während der Vorwarnung, ohne den Fokus zu stehlen.',
    set_grace: 'Schonfrist zum Verschieben',
    set_grace_help: 'In den ersten Sekunden einer Pause kannst du sie noch verschieben – Esc verschiebt sofort.',
    set_flex_only_note: 'Nur ohne Pflicht-Pause relevant',
    set_snooze: 'Verschieben um',
    set_snooze_help: 'Standardzeit für „Verschieben“ und das Tastenkürzel.',
    set_max_snoozes: 'Max. Verschiebungen',
    set_max_snoozes_help: 'Wie oft eine Pause höchstens verschoben werden kann.',

    grp_breaks: 'Pausen',
    grp_breaks_desc: 'Wie sich Pausen verhalten.',
    set_lock: 'Bildschirm sperren',
    set_lock_help: 'Legt während der Pause eine getönte Vollbild-Ansicht über deinen Desktop. Ohne Sperre erinnern nur Benachrichtigung und Widget.',
    set_lock_strict_note: 'Ohne Bildschirmsperre läuft die Pflicht-Pause unsichtbar im Hintergrund – Aktionen und Beenden bleiben trotzdem bis zum Ende gesperrt.',
    set_all_displays: 'Auf allen Bildschirmen',
    set_all_displays_help: 'Die Pausen-Ansicht erscheint auf jedem angeschlossenen Monitor.',
    set_exercises: 'Augenübungen anzeigen',
    set_exercises_help: 'Geführte Übungen während der Pause.',
    set_strict: 'Pflicht-Pause',
    set_strict_help: 'Die Pause lässt sich weder überspringen noch verschieben oder beenden – der Bildschirm wird erst nach Ablauf wieder freigegeben. Verschieben geht nur vorher, während der Vorwarnung.',
    set_strict_break_note: 'Während einer laufenden Pause nicht änderbar',
    set_overlay_opacity: 'Transparenz des Sperrbildschirms',
    set_overlay_opacity_help: 'Wie stark der Sperrbildschirm deinen Desktop abdunkelt. Die Vorschau zeigt, wie es aussieht.',
    set_skip_hold: 'Überspringen gedrückt halten',
    set_skip_hold_help: 'Schützt vor versehentlichem Abbrechen der Pause.',
    set_sound: 'Ton',
    set_sound_help: 'Sanfter Klang zu Beginn und am Ende der Pause.',
    set_volume: 'Lautstärke',

    grp_idle: 'Abwesenheit',
    grp_idle_desc: 'Erkennt, wenn du nicht am Rechner bist.',
    set_idle: 'Abwesenheit erkennen',
    set_idle_help: 'Hält den Timer an, solange du nicht am Rechner bist.',
    set_idle_after: 'Als Pause werten nach',
    set_idle_after_help: 'Wer so lange weg war, hat eine natürliche Pause gemacht – der Timer beginnt neu.',

    grp_water: 'Trinken',
    grp_water_desc: 'Erinnerungen, genug Wasser zu trinken.',
    set_water: 'Trinkerinnerung',
    set_water_help: 'Erinnert dich regelmäßig an ein Glas Wasser.',
    set_water_interval: 'Intervall',
    set_water_interval_help: 'Zeit zwischen zwei Erinnerungen.',
    set_water_goal: 'Tagesziel',
    set_water_goal_help: 'Gläser pro Tag.',
    set_glass: 'Glasgröße',
    water_daily_summary: 'Tagesziel: {total} ({n} × {ml})',

    grp_schedule: 'Arbeitszeiten',
    grp_schedule_desc: 'Erinnerungen nur, wenn du arbeitest.',
    set_hours: 'Nur während der Arbeitszeit',
    set_hours_help: 'Außerhalb pausiert AugenPause automatisch.',
    set_days: 'Tage',
    set_time: 'Uhrzeit',
    set_time_help: 'Beginn und Ende deines Arbeitstags.',
    set_time_start: 'Beginn',
    set_time_end: 'Ende',
    schedule_summary: '{days} · {start}–{end} · {duration} pro Tag',

    grp_widget: 'Widget',
    grp_widget_desc: 'Die kleine schwebende Uhr auf deinem Desktop.',
    set_widget_visible: 'Widget anzeigen',
    set_widget_visible_help: 'Kompakter Countdown mit Schnellaktionen.',
    set_widget_top: 'Immer im Vordergrund',
    set_widget_top_help: 'Bleibt über anderen Fenstern sichtbar.',
    set_widget_size: 'Größe',
    size_small: 'Klein',
    size_medium: 'Mittel',
    size_large: 'Groß',
    set_widget_opacity: 'Deckkraft',
    set_widget_seconds: 'Sekundenzeiger',
    set_widget_seconds_help: 'Zeigt einen dezent laufenden Sekundenzeiger.',
    set_widget_position: 'Position',
    set_widget_position_help: 'Setzt das Widget zurück in die obere rechte Ecke.',
    btn_reset_position: 'Zurücksetzen',

    grp_appearance: 'Darstellung',
    grp_appearance_desc: 'Farben, Design und Sprache.',
    set_theme: 'Design',
    theme_system: 'System',
    theme_dark: 'Dunkel',
    theme_light: 'Hell',
    set_accent: 'Akzentfarbe',
    accent_teal: 'Türkis',
    accent_violet: 'Violett',
    accent_blue: 'Blau',
    accent_green: 'Grün',
    accent_orange: 'Orange',
    accent_pink: 'Pink',
    set_language: 'Sprache',
    set_language_help: 'System folgt der Sprache deines Betriebssystems.',
    lang_system: 'System',

    grp_general: 'Allgemein',
    grp_general_desc: 'Start, Benachrichtigungen und Tastenkürzel.',
    set_autostart: 'Beim Anmelden starten',
    set_autostart_help: 'AugenPause startet automatisch mit deinem System.',
    set_notifications: 'Benachrichtigungen',
    set_notifications_help: 'Systembenachrichtigungen für Vorwarnungen und Trinkerinnerungen.',
    set_shortcuts: 'Globale Tastenkürzel',
    set_shortcuts_help: 'Funktionieren auch, wenn AugenPause im Hintergrund läuft.',

    grp_reset: 'Zurücksetzen',
    grp_reset_desc: 'Stellt die Standardwerte wieder her.',
    set_reset: 'Einstellungen zurücksetzen',
    set_reset_help: 'Alle Einstellungen auf Standard. Deine Statistik bleibt erhalten.',
    btn_reset_settings: 'Zurücksetzen …',
    confirm_question: 'Wirklich?',
    btn_confirm_reset: 'Ja, zurücksetzen',
    btn_cancel: 'Abbrechen',

    // ---- stats -------------------------------------------------------------------------
    stats_title: 'Statistik',
    stats_subtitle: 'Deine Pausen und Gewohnheiten im Überblick.',
    range_label: 'Zeitraum',
    range_days: '{n} Tage',
    today: 'Heute',
    today_short: 'Heute',
    kpi_breaks: 'Pausen gesamt',
    kpi_quote: 'Quote',
    kpi_screen: 'Ø Bildschirmzeit/Tag',
    kpi_water: 'Wasser Ø/Tag',
    kpi_natural: 'Natürliche Pausen',
    kpi_quote_sub: '{short} kurz · {long} lang',
    kpi_no_breaks: 'Noch keine Pausen',
    kpi_active_days_one: 'an {n} aktiven Tag',
    kpi_active_days_other: 'an {n} aktiven Tagen',
    kpi_no_data: 'Noch keine Daten',
    kpi_water_sub: 'Ziel {goal} · an {reached} von {n} Tagen erreicht',
    kpi_natural_sub: 'Abwesenheit ab {duration}',
    chart_breaks: 'Pausen pro Tag',
    chart_breaks_sub: 'Letzte {n} Tage · Ø {avg} Pausen an aktiven Tagen',
    chart_water: 'Wasser pro Tag',
    chart_water_sub: 'Tagesziel: {goal} Gläser ({ml} ml)',
    legend_completed: 'Gemacht',
    legend_skipped: 'Übersprungen',
    legend_glasses: 'Gläser',
    tip_snoozed: 'verschoben',
    tip_screen: 'Bildschirmzeit',
    tip_amount: 'getrunken',
    goal_label: 'Ziel {n}',
    empty_title: 'Noch keine Daten',
    empty_text: 'Deine Statistik füllt sich, sobald du die ersten Pausen machst. Schau später wieder vorbei!',
    stats_reset_title: 'Statistik zurücksetzen',
    stats_reset_desc: 'Löscht alle gespeicherten Tageswerte. Einstellungen bleiben erhalten.',
    btn_reset_stats: 'Statistik löschen …',

    // ---- exercises ---------------------------------------------------------------------
    ex_title: 'Übungen',
    ex_subtitle: 'Kleine Übungen, die deine Augen entspannen.',
    ex_banner_title: 'Bereit für eine Pause?',
    ex_banner_desc: 'Während der Pause führt dich AugenPause Schritt für Schritt durch passende Übungen.',
    ex_start_break: 'Jetzt Pause starten',

    ex_far_title: '20-20-20-Regel',
    ex_far_duration: '20 Sek',
    ex_far_step1: 'Alle 20 Minuten den Blick vom Bildschirm lösen.',
    ex_far_step2: 'Einen Punkt in etwa 6 Metern Entfernung suchen.',
    ex_far_step3: '20 Sekunden lang entspannt in die Ferne schauen.',

    ex_blink_title: 'Bewusst blinzeln',
    ex_blink_duration: '30 Sek',
    ex_blink_step1: 'Augen sanft schließen, kurz halten und wieder öffnen.',
    ex_blink_step2: '10- bis 15-mal langsam wiederholen.',
    ex_blink_step3: 'Das befeuchtet die Augen und beugt Trockenheit vor.',

    ex_roll_title: 'Augen kreisen',
    ex_roll_duration: '30 Sek',
    ex_roll_step1: 'Kopf ruhig halten, nur die Augen bewegen.',
    ex_roll_step2: 'Langsam fünf Kreise im Uhrzeigersinn ziehen.',
    ex_roll_step3: 'Danach fünf Kreise in die Gegenrichtung.',

    ex_nearfar_title: 'Nah-Fern-Fokus',
    ex_nearfar_duration: '1 Min',
    ex_nearfar_step1: 'Den Daumen auf Armlänge vor das Gesicht halten.',
    ex_nearfar_step2: 'Drei Sekunden den Daumen, dann einen fernen Punkt fixieren.',
    ex_nearfar_step3: 'Zehnmal im Wechsel wiederholen.',

    ex_palming_title: 'Palming',
    ex_palming_duration: '1 Min',
    ex_palming_step1: 'Handflächen aneinander reiben, bis sie warm sind.',
    ex_palming_step2: 'Hohle Hände locker über die geschlossenen Augen legen.',
    ex_palming_step3: 'Ruhig atmen und die Dunkelheit wirken lassen.',

    ex_eight_title: 'Acht nachzeichnen',
    ex_eight_duration: '30 Sek',
    ex_eight_step1: 'Eine große liegende Acht vor dir an der Wand vorstellen.',
    ex_eight_step2: 'Sie langsam und gleichmäßig mit den Augen nachfahren.',
    ex_eight_step3: 'Nach der Hälfte der Zeit die Richtung wechseln.',

    ex_neck_title: 'Nacken & Schultern lockern',
    ex_neck_duration: '1 Min',
    ex_neck_step1: 'Schultern langsam hochziehen und locker fallen lassen.',
    ex_neck_step2: 'Kopf sanft zur Seite neigen und 10 Sekunden halten.',
    ex_neck_step3: 'Seite wechseln und ruhig weiteratmen.',

    ex_water_title: 'Aufstehen & Wasser trinken',
    ex_water_duration: '2 Min',
    ex_water_step1: 'Aufstehen, strecken und ein paar Schritte gehen.',
    ex_water_step2: 'In Ruhe ein Glas Wasser trinken.',
    ex_water_step3: 'Dabei kurz aus dem Fenster in die Ferne schauen.',

    // ---- about -------------------------------------------------------------------------
    about_title: 'Über AugenPause',
    about_subtitle: 'Gesunde Bildschirmgewohnheiten – ohne Kompromisse bei der Privatsphäre.',
    about_version: 'Version {version}',
    about_version_unknown: 'Entwicklerversion',
    about_tagline: 'Deine Augen werden es dir danken.',
    about_desc: 'AugenPause erinnert dich an regelmäßige Augenpausen und ans Trinken, erkennt Meetings und Abwesenheit und hilft dir mit kurzen Übungen, entspannt und konzentriert zu bleiben.',
    about_privacy: 'Datenschutz',
    about_privacy_text: 'Alle Daten bleiben lokal auf deinem Gerät. Keine Konten, keine Cloud, keine Netzwerkverbindungen.',
    about_privacy_b1: 'Einstellungen und Statistik liegen nur in deinem Benutzerordner',
    about_privacy_b2: 'Keine Telemetrie, keine Analyse, kein Tracking',
    about_privacy_b3: 'Meeting-Erkennung prüft nur, ob Kamera oder Mikrofon aktiv sind – nie Inhalte',
    about_security: 'Sicherheit',
    about_sec_sandbox: 'Alle Fenster laufen in einer Sandbox',
    about_sec_isolation: 'Context-Isolation zwischen Oberfläche und System',
    about_sec_csp: 'Strikte Content-Security-Policy',
    about_sec_scripts: 'Keine Fremd-Skripte, keine Web-Fonts, keine externen Inhalte',
    about_lock: 'Pausen-Sperre',
    about_lock_text: 'Bei einer Pflicht-Pause legt AugenPause eine getönte Schicht über den ganzen Bildschirm: Dein Desktop bleibt dahinter sichtbar, ist aber nicht mehr bedienbar. Die Sperre endet ausschließlich nach Ablauf der Zeit – es gibt bewusst keinen Weg, sie vorher zu beenden.',
    about_lock_b1: 'Wie stark die Tönung deckt, bestimmst du selbst (Deckkraft 20–100 %).',
    about_lock_b2: 'Wird AugenPause während einer Pause hart beendet, läuft die Pause beim nächsten Start weiter – sofern das weniger als 8 Stunden her ist.',
    about_lock_b3: 'Unter Linux braucht die durchscheinende Darstellung einen aktiven Compositor.',
    about_lock_win: 'Strg+Alt+Entf und Win+L bleiben bewusst immer verfügbar.',
    about_lock_mac: '⌃⌘Q (Bildschirm sperren) und ⌥⌘⎋ (Sofort beenden) bleiben bewusst immer verfügbar.',
    about_lock_linux: 'Die System-Tastenkürzel deiner Desktop-Umgebung, z. B. zum Sperren, bleiben bewusst immer verfügbar.',
    about_shortcuts: 'Tastenkürzel',
    about_shortcuts_note: 'Global, solange „Globale Tastenkürzel“ aktiviert ist. Im Dashboard wechselt {mod} + 1–5 den Bereich.',
    about_license: 'Lizenz',
    about_license_text: 'MIT-Lizenz – frei nutzbar, veränderbar und weitergebbar, ohne Gewährleistung.',
    about_footer: 'Gemacht für gesündere Tage am Bildschirm.',
  },

  en: {
    app_name: 'AugenPause',
    view_error: 'This section could not be loaded.',

    nav_label: 'Main navigation',
    nav_overview: 'Overview',
    nav_settings: 'Settings',
    nav_stats: 'Statistics',
    nav_exercises: 'Exercises',
    nav_about: 'About',

    phase_work: 'Focus time',
    phase_warning: 'Break soon',
    phase_break_short: 'Short break',
    phase_break_long: 'Long break',
    phase_meeting: 'In a meeting',
    phase_paused: 'Paused',
    phase_away: 'Away',
    phase_off_hours: 'Off hours',
    meeting_active_chip: 'In a meeting',

    mini_until_break: 'until break',
    mini_remaining: 'remaining',
    mini_meeting: 'break follows later',
    mini_until_resume: 'until resume',
    mini_indefinite: 'until you resume',
    mini_frozen: 'timer on hold',
    mini_no_reminders: 'no reminders',
    mini_next_start: 'next start',

    toast_saved: 'Saved',
    toast_save_failed: 'Could not save',
    toast_action_failed: 'Not possible right now',
    toast_settings_reset: 'Settings reset',
    toast_reset_blocked: 'Not possible while a break is running',
    toast_stats_reset: 'Statistics reset',
    toast_resumed: 'Reminders resumed',
    toast_break_ended: 'Break ended',
    toast_snoozed: 'Break snoozed by {duration}',
    toast_skipped: 'Break skipped',
    toast_paused_for: 'Paused for {duration}',
    toast_paused_tomorrow: 'Paused until tomorrow',
    toast_paused: 'Paused until you resume',
    toast_timer_reset: 'Timer reset',
    toast_drink: 'Cheers! Glass logged',
    toast_position_reset: 'Widget position reset',

    overview_title: 'Overview',
    greet_night: 'Good night',
    greet_morning: 'Good morning',
    greet_day: 'Hello',
    greet_evening: 'Good evening',
    hero_label: 'Current status',
    today_label: 'Today',

    act_resume: 'Resume',
    act_end_break: 'End break',
    act_break_now: 'Break now',
    act_edit_hours: 'Edit working hours',
    act_snooze: 'Snooze',
    act_snooze_options: 'Snooze by …',
    act_skip: 'Skip',
    act_meeting_mode: 'Meeting mode',
    act_pause: 'Pause',
    act_reset_timer: 'Reset timer',

    menu_snooze_heading: 'Snooze break by',
    menu_meeting_heading: 'No breaks during the meeting',
    menu_pause_heading: 'Pause reminders',
    pause_tomorrow: 'Until tomorrow',
    pause_indefinite: 'Until I resume',

    snooze_grace_any: 'Grace period – snoozing always allowed',
    snooze_left: 'Can be snoozed {n}× more',
    snooze_none_left: 'No snoozes left',
    snooze_disabled: 'Snoozing is disabled',
    snooze_strict: 'Mandatory break – cannot be snoozed',
    snooze_used: 'Snoozed {count}× · {left}× left',

    break_short_lc: 'short break',
    break_long_lc: 'long break',

    center_until_break: 'until break',
    center_break_soon: 'break soon',
    center_remaining: 'remaining',
    center_in_meeting: 'in meeting',
    center_until_resume: 'until resume',
    center_indefinite: 'indefinitely',
    center_frozen: 'on hold',
    center_next_start: 'next start',

    title_next: 'Next: {type} · {duration}',
    title_meeting: 'Meeting detected – your break will follow afterwards',
    title_break_short: 'Time for your eyes',
    title_break_long: 'Time to get up and move',
    title_paused: 'Reminders paused',
    title_away: 'You are away from your computer',
    title_off_hours: 'Outside your working hours',

    detail_starts_at: 'Starts at {time}',
    detail_this_long: 'This one is a long break',
    detail_long_in_one: 'Long break after the next one',
    detail_long_in_other: 'Long break in {n} breaks',
    detail_meeting_since: 'In a meeting since {time}',
    detail_meeting_after: 'The {type} ({duration}) starts shortly after the meeting',
    detail_ends_at: 'Ends at {time}',
    detail_paused_until: 'Until {time}',
    detail_paused_until_day: 'Until {day}, {time}',
    detail_paused_indefinite: 'Until you resume',
    detail_paused_hint: 'Resuming starts a fresh work period',
    detail_away_since: 'Away since {time}',
    detail_away_rule: 'After {duration} your absence counts as a break',
    detail_hours: '{days} · {start}–{end}',
    detail_next_start: 'Next start: {day}, {time}',

    notice_grace: 'Grace period: {s} s left – you can always snooze now.',
    notice_strict: 'Mandatory break: this break runs until the end – your screen is released automatically afterwards.',

    tile_breaks: 'Breaks taken',
    tile_screen: 'Screen time',
    tile_water: 'Water',
    tile_quote: 'Break rate',
    sub_skipped_one: '{n} skipped',
    sub_skipped_other: '{n} skipped',
    sub_natural_one: '{n} natural',
    sub_natural_other: '{n} natural',
    sub_snoozed_one: 'snoozed {n}×',
    sub_snoozed_other: 'snoozed {n}×',
    sub_break_time: '{duration} on breaks',
    sub_screen_hint: 'Active time today',
    sub_water_ml: '{ml} of {goal}',
    sub_water_next: 'Next reminder in {duration}',
    sub_water_goal: 'Daily goal reached',
    sub_quote_empty: 'No breaks yet today',
    sub_quote: '{done} of {total} breaks',
    water_undo: 'Remove last glass',
    water_add: 'Log a glass of water',
    water_due: 'Time for a glass of water',

    tip_title: 'Tip of the day',
    tip_prev: 'Previous tip',
    tip_next: 'Next tip',
    tip_0: 'Follow the 20-20-20 rule: every 20 minutes, look at something about 20 feet (6 m) away for 20 seconds.',
    tip_1: 'We blink up to 60% less at a screen. Blink deliberately to prevent dry eyes.',
    tip_2: 'Keep your monitor about an arm’s length away – with the top edge at or slightly below eye level.',
    tip_3: 'Match the brightness to your surroundings: your screen should not be brighter than the room around you.',
    tip_4: 'Avoid glare: place your screen at a right angle to the window where possible.',
    tip_5: 'Drink water regularly – even mild dehydration can make your eyes feel dry.',
    tip_6: 'Daylight does you good: spend your long break outside if you can.',
    tip_7: 'Increase the font size instead of leaning towards the screen – your eyes and neck will thank you.',
    tip_8: 'Dry heating air? Airing the room regularly helps your eyes too.',
    tip_9: 'Have your eyesight checked regularly – and mention how much you work at a screen.',
    tip_10: 'Balanced contrast matters more than light or dark – pick whatever feels comfortable to you.',
    tip_11: 'Palming relaxes: cup your hands over your closed eyes and breathe calmly for a minute.',
    tip_12: 'Frequent short breaks work better than rare long ones – regularity is key.',
    tip_13: 'Skip the phone during your break – it is no rest for your eyes.',

    day_short_0: 'Sun',
    day_short_1: 'Mon',
    day_short_2: 'Tue',
    day_short_3: 'Wed',
    day_short_4: 'Thu',
    day_short_5: 'Fri',
    day_short_6: 'Sat',
    days_all: 'Every day',

    settings_title: 'Settings',
    settings_subtitle: 'Changes apply immediately.',
    jump_label: 'Jump to section',

    err_end_after_start: 'The end must be after the start.',
    err_invalid: 'This value is not valid.',
    err_generic: 'Some changes could not be applied.',
    err_days_empty: 'Select at least one day.',

    value_off: 'Off',
    value_click: 'Click',
    value_never: 'Never',
    value_opacity: '{n} % opacity',
    unit_glasses: 'glasses',

    grp_timer: 'Timer',
    grp_timer_desc: 'How often and how long you take breaks.',
    set_preset: 'Preset',
    set_preset_help: 'Proven rhythms – or your own values.',
    preset_halfhour: 'Half-hourly',
    preset_hourly: 'Hourly',
    preset_202020: '20-20-20',
    preset_pomodoro: 'Pomodoro',
    preset_custom: 'Custom',
    preset_custom_meta: 'Your values',
    summary_short_seconds: 'Every {work} a {n}-second break',
    summary_short_minutes: 'Every {work} a {n}-min break',
    summary_short_mixed: 'Every {work} a break of {duration}',
    summary_long: ', every {nth} break lasts {duration}.',
    summary_end: '.',
    set_work: 'Work time',
    set_work_help: 'Time until the next break.',
    set_short: 'Short break',
    set_short_help: 'Even 20 seconds help – 1 to 5 minutes is ideal.',
    set_long_enabled: 'Long break',
    set_long_enabled_help: 'A regular longer break to get up and move.',
    set_long_duration: 'Long break duration',
    set_long_duration_help: 'Enough time to stand up and have a drink.',
    set_long_every: 'Every Nth break',
    set_long_every_help: 'How often a break becomes a long break.',

    grp_meeting: 'Meetings & interruptions',
    grp_meeting_short: 'Meetings',
    grp_meeting_desc: 'So a break never surprises you in the middle of a call. Meetings only postpone a break before it starts – a running mandatory break ends only when the time is up.',
    set_meeting_detect: 'Detect meetings automatically',
    set_meeting_detect_help: 'Windows/Linux: camera or microphone in use · macOS: call apps like Zoom, Teams, Meet',
    set_warn: 'Advance warning',
    set_warn_help: 'Announces the break beforehand – with one-click snooze.',
    set_show_on_warning: 'Show widget on warning',
    set_show_on_warning_help: 'Shows the hidden widget during the warning without stealing focus.',
    set_grace: 'Snooze grace period',
    set_grace_help: 'During the first seconds of a break you can still snooze it – Esc snoozes instantly.',
    set_flex_only_note: 'Only relevant without mandatory break',
    set_snooze: 'Snooze by',
    set_snooze_help: 'Default time for “Snooze” and the keyboard shortcut.',
    set_max_snoozes: 'Max. snoozes',
    set_max_snoozes_help: 'How many times a break can be snoozed.',

    grp_breaks: 'Breaks',
    grp_breaks_desc: 'How breaks behave.',
    set_lock: 'Lock screen',
    set_lock_help: 'Lays a tinted full-screen view over your desktop during breaks. Without it, only a notification and the widget remind you.',
    set_lock_strict_note: 'Without the lock screen the mandatory break runs invisibly in the background – actions and quitting stay blocked until it is over.',
    set_all_displays: 'On all displays',
    set_all_displays_help: 'The break view appears on every connected monitor.',
    set_exercises: 'Show eye exercises',
    set_exercises_help: 'Guided exercises during the break.',
    set_strict: 'Mandatory break',
    set_strict_help: 'The break can neither be skipped nor snoozed or ended – your screen is only released once the time is up. Snoozing is only possible beforehand, during the advance warning.',
    set_strict_break_note: 'Cannot be changed while a break is running',
    set_overlay_opacity: 'Break screen tint',
    set_overlay_opacity_help: 'How much the break screen dims your desktop. The preview shows what it looks like.',
    set_skip_hold: 'Hold to skip',
    set_skip_hold_help: 'Protects against ending a break by accident.',
    set_sound: 'Sound',
    set_sound_help: 'A gentle chime when a break starts and ends.',
    set_volume: 'Volume',

    grp_idle: 'Absence',
    grp_idle_desc: 'Detects when you are away from your computer.',
    set_idle: 'Detect absence',
    set_idle_help: 'Holds the timer while you are away.',
    set_idle_after: 'Count as break after',
    set_idle_after_help: 'Being away this long counts as a natural break – the timer starts over.',

    grp_water: 'Hydration',
    grp_water_desc: 'Reminders to drink enough water.',
    set_water: 'Drink reminder',
    set_water_help: 'Regularly reminds you to have a glass of water.',
    set_water_interval: 'Interval',
    set_water_interval_help: 'Time between two reminders.',
    set_water_goal: 'Daily goal',
    set_water_goal_help: 'Glasses per day.',
    set_glass: 'Glass size',
    water_daily_summary: 'Daily goal: {total} ({n} × {ml})',

    grp_schedule: 'Working hours',
    grp_schedule_desc: 'Only remind you while you work.',
    set_hours: 'Only during working hours',
    set_hours_help: 'Outside of them AugenPause pauses automatically.',
    set_days: 'Days',
    set_time: 'Time',
    set_time_help: 'Start and end of your working day.',
    set_time_start: 'Start',
    set_time_end: 'End',
    schedule_summary: '{days} · {start}–{end} · {duration} per day',

    grp_widget: 'Widget',
    grp_widget_desc: 'The small floating clock on your desktop.',
    set_widget_visible: 'Show widget',
    set_widget_visible_help: 'Compact countdown with quick actions.',
    set_widget_top: 'Always on top',
    set_widget_top_help: 'Stays visible above other windows.',
    set_widget_size: 'Size',
    size_small: 'Small',
    size_medium: 'Medium',
    size_large: 'Large',
    set_widget_opacity: 'Opacity',
    set_widget_seconds: 'Seconds hand',
    set_widget_seconds_help: 'Shows a subtle running seconds hand.',
    set_widget_position: 'Position',
    set_widget_position_help: 'Moves the widget back to the top-right corner.',
    btn_reset_position: 'Reset',

    grp_appearance: 'Appearance',
    grp_appearance_desc: 'Colours, theme and language.',
    set_theme: 'Theme',
    theme_system: 'System',
    theme_dark: 'Dark',
    theme_light: 'Light',
    set_accent: 'Accent colour',
    accent_teal: 'Teal',
    accent_violet: 'Violet',
    accent_blue: 'Blue',
    accent_green: 'Green',
    accent_orange: 'Orange',
    accent_pink: 'Pink',
    set_language: 'Language',
    set_language_help: 'System follows your operating system language.',
    lang_system: 'System',

    grp_general: 'General',
    grp_general_desc: 'Startup, notifications and shortcuts.',
    set_autostart: 'Start at login',
    set_autostart_help: 'AugenPause starts automatically with your system.',
    set_notifications: 'Notifications',
    set_notifications_help: 'System notifications for warnings and drink reminders.',
    set_shortcuts: 'Global shortcuts',
    set_shortcuts_help: 'Work even while AugenPause runs in the background.',

    grp_reset: 'Reset',
    grp_reset_desc: 'Restores the default values.',
    set_reset: 'Reset settings',
    set_reset_help: 'All settings back to default. Your statistics are kept.',
    btn_reset_settings: 'Reset …',
    confirm_question: 'Are you sure?',
    btn_confirm_reset: 'Yes, reset',
    btn_cancel: 'Cancel',

    stats_title: 'Statistics',
    stats_subtitle: 'Your breaks and habits at a glance.',
    range_label: 'Time range',
    range_days: '{n} days',
    today: 'Today',
    today_short: 'Today',
    kpi_breaks: 'Total breaks',
    kpi_quote: 'Break rate',
    kpi_screen: 'Avg. screen time/day',
    kpi_water: 'Avg. water/day',
    kpi_natural: 'Natural breaks',
    kpi_quote_sub: '{short} short · {long} long',
    kpi_no_breaks: 'No breaks yet',
    kpi_active_days_one: 'on {n} active day',
    kpi_active_days_other: 'on {n} active days',
    kpi_no_data: 'No data yet',
    kpi_water_sub: 'Goal {goal} · reached on {reached} of {n} days',
    kpi_natural_sub: 'Away for {duration} or more',
    chart_breaks: 'Breaks per day',
    chart_breaks_sub: 'Last {n} days · avg. {avg} breaks on active days',
    chart_water: 'Water per day',
    chart_water_sub: 'Daily goal: {goal} glasses ({ml} ml)',
    legend_completed: 'Taken',
    legend_skipped: 'Skipped',
    legend_glasses: 'Glasses',
    tip_snoozed: 'snoozed',
    tip_screen: 'screen time',
    tip_amount: 'drunk',
    goal_label: 'Goal {n}',
    empty_title: 'No data yet',
    empty_text: 'Your statistics fill up as soon as you take your first breaks. Check back later!',
    stats_reset_title: 'Reset statistics',
    stats_reset_desc: 'Deletes all stored daily values. Settings are kept.',
    btn_reset_stats: 'Delete statistics …',

    ex_title: 'Exercises',
    ex_subtitle: 'Small exercises that relax your eyes.',
    ex_banner_title: 'Ready for a break?',
    ex_banner_desc: 'During a break AugenPause guides you step by step through matching exercises.',
    ex_start_break: 'Start a break now',

    ex_far_title: '20-20-20 rule',
    ex_far_duration: '20 sec',
    ex_far_step1: 'Every 20 minutes, look away from your screen.',
    ex_far_step2: 'Find a spot about 20 feet (6 m) away.',
    ex_far_step3: 'Gaze into the distance for 20 relaxed seconds.',

    ex_blink_title: 'Conscious blinking',
    ex_blink_duration: '30 sec',
    ex_blink_step1: 'Gently close your eyes, hold briefly, then open.',
    ex_blink_step2: 'Repeat slowly 10 to 15 times.',
    ex_blink_step3: 'This moistens your eyes and prevents dryness.',

    ex_roll_title: 'Eye circles',
    ex_roll_duration: '30 sec',
    ex_roll_step1: 'Keep your head still, move only your eyes.',
    ex_roll_step2: 'Slowly draw five circles clockwise.',
    ex_roll_step3: 'Then five circles the other way.',

    ex_nearfar_title: 'Near–far focus',
    ex_nearfar_duration: '1 min',
    ex_nearfar_step1: 'Hold your thumb at arm’s length in front of you.',
    ex_nearfar_step2: 'Focus on your thumb for three seconds, then on a distant spot.',
    ex_nearfar_step3: 'Alternate ten times.',

    ex_palming_title: 'Palming',
    ex_palming_duration: '1 min',
    ex_palming_step1: 'Rub your palms together until they are warm.',
    ex_palming_step2: 'Cup them loosely over your closed eyes.',
    ex_palming_step3: 'Breathe calmly and enjoy the darkness.',

    ex_eight_title: 'Trace a figure eight',
    ex_eight_duration: '30 sec',
    ex_eight_step1: 'Imagine a large sideways eight on the wall in front of you.',
    ex_eight_step2: 'Trace it slowly and evenly with your eyes.',
    ex_eight_step3: 'Switch direction halfway through.',

    ex_neck_title: 'Loosen neck & shoulders',
    ex_neck_duration: '1 min',
    ex_neck_step1: 'Slowly raise your shoulders and let them drop.',
    ex_neck_step2: 'Gently tilt your head to one side and hold for 10 seconds.',
    ex_neck_step3: 'Switch sides and keep breathing calmly.',

    ex_water_title: 'Stand up & drink water',
    ex_water_duration: '2 min',
    ex_water_step1: 'Stand up, stretch and take a few steps.',
    ex_water_step2: 'Drink a glass of water at your own pace.',
    ex_water_step3: 'Look out of the window into the distance meanwhile.',

    about_title: 'About AugenPause',
    about_subtitle: 'Healthy screen habits – without compromising your privacy.',
    about_version: 'Version {version}',
    about_version_unknown: 'Development build',
    about_tagline: 'Your eyes will thank you.',
    about_desc: 'AugenPause reminds you to take regular eye breaks and to drink water, detects meetings and absence, and helps you stay relaxed and focused with short exercises.',
    about_privacy: 'Privacy',
    about_privacy_text: 'All data stays local on your device. No accounts, no cloud, no network connections.',
    about_privacy_b1: 'Settings and statistics live only in your user folder',
    about_privacy_b2: 'No telemetry, no analytics, no tracking',
    about_privacy_b3: 'Meeting detection only checks whether camera or microphone are in use – never any content',
    about_security: 'Security',
    about_sec_sandbox: 'All windows run in a sandbox',
    about_sec_isolation: 'Context isolation between interface and system',
    about_sec_csp: 'Strict Content Security Policy',
    about_sec_scripts: 'No third-party scripts, no web fonts, no external content',
    about_lock: 'Break lock',
    about_lock_text: 'During a mandatory break AugenPause lays a tinted layer over your whole screen: your desktop stays visible behind it but can no longer be used. The lock ends only when the time is up – by design there is no way to end it earlier.',
    about_lock_b1: 'You decide how opaque the tint is (20–100 % opacity).',
    about_lock_b2: 'If AugenPause is force-closed during a break, the break resumes at the next start – as long as that is less than 8 hours later.',
    about_lock_b3: 'On Linux the see-through tint needs a running compositor.',
    about_lock_win: 'Ctrl+Alt+Del and Win+L intentionally always remain available.',
    about_lock_mac: '⌃⌘Q (lock screen) and ⌥⌘⎋ (force quit) intentionally always remain available.',
    about_lock_linux: 'Your desktop environment’s system shortcuts, e.g. for locking, intentionally always remain available.',
    about_shortcuts: 'Keyboard shortcuts',
    about_shortcuts_note: 'Global while “Global shortcuts” is enabled. In the dashboard, {mod} + 1–5 switches sections.',
    about_license: 'Licence',
    about_license_text: 'MIT licence – free to use, modify and share, without warranty.',
    about_footer: 'Made for healthier days at the screen.',
  },
};
