// Widget strings (de + en). Used via createT() from ../shared/i18n.js.

export default {
  de: {
    // face labels
    phaseWork: 'Pause in',
    phaseWarning: 'Gleich Pause',
    phaseBreakShort: 'Augenpause',
    phaseBreakLong: 'Lange Pause',
    phasePaused: 'Pausiert',
    phaseAway: 'Abwesend',
    phaseOffHours: 'Feierabend',
    phaseMeeting: 'Meeting',
    infinity: '∞',
    noCountdown: '–:–',

    // accessibility summaries
    clockButton: 'AugenPause – Dashboard ein-/ausblenden',
    ariaWork: 'Nächste Pause in {time}',
    ariaWorkLong: 'Nächste lange Pause in {time}',
    ariaWarning: 'Pause beginnt in {time}',
    ariaBreakShort: 'Augenpause läuft, noch {time}',
    ariaBreakLong: 'Lange Pause läuft, noch {time}',
    ariaPausedUntil: 'Erinnerungen pausiert, noch {time}',
    ariaPaused: 'Erinnerungen pausiert',
    ariaAway: 'Abwesend – Timer angehalten',
    ariaOffHours: 'Feierabend – keine Erinnerungen',
    ariaMeeting: 'Meeting erkannt – Pause wird zurückgehalten',
    ariaMeetingActive: 'Meeting erkannt',
    ariaWater: 'Wasser: {count} von {goal} Gläsern',
    ariaWaterDue: 'Zeit für ein Glas Wasser',
    ariaNoData: 'AugenPause',

    // hover pill
    actionsLabel: 'Schnellaktionen',
    breakNow: 'Jetzt Pause machen',
    pause: 'Erinnerungen pausieren',
    resume: 'Erinnerungen fortsetzen',
    drink: 'Glas Wasser getrunken (+1)',
    drinkBadge: '{count}/{goal}',
    dashboard: 'Dashboard ein-/ausblenden',

    // warning pill
    warnIn: 'Pause in',
    warnNow: 'Jetzt',
    warnNowTitle: 'Pause jetzt starten',
    snooze: '+{min}',
    snoozeTitle: 'Pause um {min} Min verschieben',
    snoozeDisabledTitle: 'Verschieben nicht mehr möglich',

    // break pill
    breakPill: 'Pause',
    breakPillLong: 'Lange Pause',
    endBreak: 'Beenden',
    endBreakTitle: 'Pause vorzeitig beenden',
    strictTitle: 'Pflicht-Pause – endet automatisch nach Ablauf',
    lockedTitle: 'Die Pause kann hier nicht beendet werden',
  },
  en: {
    phaseWork: 'Break in',
    phaseWarning: 'Break soon',
    phaseBreakShort: 'Eye break',
    phaseBreakLong: 'Long break',
    phasePaused: 'Paused',
    phaseAway: 'Away',
    phaseOffHours: 'Off hours',
    phaseMeeting: 'Meeting',
    infinity: '∞',
    noCountdown: '–:–',

    clockButton: 'AugenPause – toggle dashboard',
    ariaWork: 'Next break in {time}',
    ariaWorkLong: 'Next long break in {time}',
    ariaWarning: 'Break starts in {time}',
    ariaBreakShort: 'Eye break running, {time} left',
    ariaBreakLong: 'Long break running, {time} left',
    ariaPausedUntil: 'Reminders paused, {time} left',
    ariaPaused: 'Reminders paused',
    ariaAway: 'Away – timer stopped',
    ariaOffHours: 'Off hours – no reminders',
    ariaMeeting: 'Meeting detected – break on hold',
    ariaMeetingActive: 'Meeting detected',
    ariaWater: 'Water: {count} of {goal} glasses',
    ariaWaterDue: 'Time for a glass of water',
    ariaNoData: 'AugenPause',

    actionsLabel: 'Quick actions',
    breakNow: 'Take a break now',
    pause: 'Pause reminders',
    resume: 'Resume reminders',
    drink: 'Drank a glass of water (+1)',
    drinkBadge: '{count}/{goal}',
    dashboard: 'Toggle dashboard',

    warnIn: 'Break in',
    warnNow: 'Now',
    warnNowTitle: 'Start the break now',
    snooze: '+{min}',
    snoozeTitle: 'Snooze break for {min} min',
    snoozeDisabledTitle: 'No snoozes left',

    breakPill: 'Break',
    breakPillLong: 'Long break',
    endBreak: 'End',
    endBreakTitle: 'End break early',
    strictTitle: 'Mandatory break – ends automatically when time is up',
    lockedTitle: 'This break cannot be ended here',
  },
};
